# Generated by Django 4.2.7 on 2023-12-19 13:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 19, 20, 15, 5, 56073, tzinfo=datetime.timezone.utc)),
        ),
    ]
