# Generated by Django 5.0 on 2024-01-08 10:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_user_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='prefix',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 8, 17, 57, 12, 466709, tzinfo=datetime.timezone.utc)),
        ),
    ]
